baseURL: https://example.com
languageCode: en-us
defaultContentLanguage: en
title: tangjing
theme: hello-friend-ng
googleAnalytics: UA-123456789-1
disqusShortname: jessietang
enableGitInfo: true
copyright: 唐静  1994-2020

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  homeSubtitle: 2年RN，3年前端。
  # keywords: 123 456 789
  # description: "2年RN，3年前端。"
  # footer: Copyright@1994-2020  唐静<br/>Supported by [Hugo](https://gohugo.io/). <br/>Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # # For more date formats see https://gohugo.io/functions/format/
  # dateFormat: Jan 2, 2006
  # codePenUser: someUser
  # katex: true
  # logo:
  #   -logoText: $ cd /home/
  #   -logoHomeLink: /

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
